### ISSUE TITLE
how should file de-duplication be represented?

### ISSUE THREAD

**Issue by wanderview** [kinu/quota-api#11]
I understand blink plans to add file de-duplication for their Cache API implementation.  My impression is they are planning to de-duplicate across both Cache API origins and the http cache, but I'm not sure.

How should the quota system account for de-duplicated files?

What happens if an origin thinks they are within their quota, but then the http cache ages out a de-duped file causing it to be solely owned by that origin?  Does its usage suddenly go up and trigger further quota eviction?

**Comment by kinu** [comment]
How de-duplication should work with quota is an interesting question.  My initial feeling is that the amount of data and quota should be simply calculated before/without de-duplication, but eviction may kick in if the overall available space becomes low because more (different) data is cached after de-duped file becomes solely owned one?
/cc @jkarlin @inexorabletash

**Comment by kinu** [comment]
Moved to https://github.com/w3c/quota-api/issues/1
